### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by NALStudio** [KL-Corporation/Koponen-Dating-Simulator#75]
- [x] Story Chapter 1
- [x] Story Chapter 2 (target: 18.6)
- [x] Story Chapter 3
- [x] Story Chapter 4
- [x] Story Chapter 5
- [x] Story Chapter 6
- [x] Story Chapter 7 (target: 22.6)
- [x] ~~Story Chapter 8 (target: 30.6)~~
- [x] ~~Story Chapter 9~~
- [x] Story Chapter 10 (target: 10.7)
- [x] Tombstones for bad ending
- [x] Niko playthrough
- [x] Aaro playthrough
- [x] Songs for story chapters
- [x] ~~Songs depending on state for final story chapter~~
- [x] Add teleport bases to Campaign 06 (blue hologram cone light on top)
- [x] Add backgrounds to story and campaign menus

__(~~strikethrough~~ todos are scrapped, because we don't have time to make it to release)__
